on: [push]
name: Coutils CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Run tests."
        uses: actions-rs/cargo@v1
        with:
          command: test 
          args: --features=clone,filesystem -- --show-output
      - name: "Generate documentation."
        uses: actions-rs/cargo@v1
        with:
          command: doc
      - name: "Deploy the documentation."
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: target/doc/coutils
